---
- name: Create web root folder
  file: path=/var/html state=directory  
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "CentOS"

- name: Configure nginx web root folder in ubuntu
  copy: src=default_ubuntu dest=/etc/nginx/sites-available/default
  when: ansible_distribution == "Ubuntu"
  notify:
     - Restart nginx server

- name: Configure nginx web root folder in Centos
  copy: src=default_centos.conf dest=/etc/nginx/conf.d/default.conf
  when: ansible_distribution == "CentOS"
  notify:
     - Restart nginx server
